# Generated by Django 5.2.3 on 2025-06-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0002_statusreport_delete_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='content',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
