# Generated by Django 5.2.3 on 2025-06-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0003_alter_statusreport_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
