# Generated by Django 5.2.3 on 2025-06-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0005_remove_statusreport_content_currentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_status',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='CurrentStatus',
        ),
    ]
