# Generated by Django 5.2.3 on 2025-06-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0006_project_current_status_delete_currentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusreport',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
