# Generated by Django 5.2.3 on 2025-06-27 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_alter_statusreport_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
    ]
