# Generated by Django 5.2.4 on 2025-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0008_remove_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanbancard',
            name='status',
            field=models.CharField(choices=[('to do', 'Todo'), ('in progress', 'In Progress'), ('done', 'Done')], max_length=50),
        ),
    ]
